version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  frontend:
    build: ./inteli-front
    ports:
      - "5173:5173"

  nodeapi:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    command: ["/usr/wait-for-it.sh", "mongodb:27017", "--", "npm", "run", "dev"]

  pythonapi:
    build: ./pyserver
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    command: ["/usr/wait-for-it.sh", "qdrant:6333", "--", "bash", "-c", "python Qdrant_IntelliTs.py && uvicorn main:app --host 0.0.0.0 --port 8000"]
    volumes:
      - data-volume:/app/data

volumes:
  mongodb-data:
  qdrant_storage:
  data-volume:
